name: jahwa_mobile_working_center
description: "Jahwa Mobile"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependency_overrides:
  crypto: ^2.1.5
  collection: ^1.14.13
  args: ^1.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2 # Cupertino Icons font
  dynamic_treeview: ^1.0.0+2 # Dynamic Treeview for Menu List
  encrypt: ^4.0.2 # Encrypt Package
  flutter_launcher_name: ^0.0.1 # App Name Setting Package
  font_awesome_flutter: ^8.8.1 # FontAwesome Icon Package
  http: ^0.12.2 # Api Connection Package
  intl: ^0.16.1 # By Locale Number, Date Format Package
  progress_dialog: ^1.2.4 # Progress Dialog Package
  select_dialog: ^1.2.0 # Select Dialog (Ex. Language Select) Package
  shared_preferences: ^0.5.10 # Global Variable of App (Same Cookie) Package
  progress_state_button: ^1.0.1 # Progress In Check Process

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5 # App Icon Setting Package -> Ref. flutter_icons

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/jahwa.png
   - assets/lang/ko.json
   - assets/lang/vi.json
   - assets/lang/zh.json
   - assets/lang/en.json
  # - assets/JHMobile.db
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Malgun # Use Windwos Malgun Font
      fonts:
        - asset: fonts/malgun.ttf
        - asset: fonts/malgunbd.ttf
        - asset: fonts/malgunsl.ttf
    - family: NanumBrush # Use Naver Nanum Font
      fonts:
        - asset: fonts/NanumBrush.ttf
    - family: NanumPen # Use Naver Nanum Font
      fonts:
        - asset: fonts/NanumPen.ttf
  #        style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# App Name Setting
flutter_launcher_name:
  name: "JH Mobile"

# App Icon Setting
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"