name: jahwa_mobile_working_center
description: "Jahwa Mobile"

version: 1.0.0+0 # For Upgrade Number - JHGWMAIN.MobileVersion보다 작은 경우 경우 /Update로 이동됨, App은 수정하고 Table의 정보는 수정하지 않으면 무의미

environment:
  sdk: ">=2.8.0 <3.0.0"

dependency_overrides:
  crypto: ^2.1.5
  collection: ^1.14.13
  args: ^1.6.0

dependencies:
  flutter:
    sdk: flutter

  awesome_notifications: any # Local Notification, IOS의 경우 별도의 설정 필요
  cron: ^0.2.3 # Background Execution - 별도로 실행되는 Thread를 생성하는 패키지, 차후 주기적으로 Check하여 메세지는 보내주는 기능을 개발할때 사용예정
  cupertino_icons: ^0.1.2 # Cupertino Icons font
  encrypt: ^4.0.2 # Encrypt Package - 암호화 처리용 패키지, /util/common.dart에서 사용
  firebase_messaging: ^7.0.3 # Firebase Cloud Messaging
  flutter_html: ^1.0.2 # HTML Viewer - HTML로 이루어진 내용을 보기위해 사용되는 패키지
  flutter_launcher_name: ^0.0.1 # App Name Setting Package
  flutter_local_notifications: ^3.0.1+6 # Notification - 상단 Status Bar에 알람참을 만드는 패키지, 휴대폰에 따라 최대 24~48개 가량 메세지가 만들어짐
  flutter_swiper: ^1.1.6 # Swipe Page - 한페이지내에서 여러화면을 Swipe할때 사용, JimsGatheringInformation.dart등에서 사용
  font_awesome_flutter: ^8.8.1 # FontAwesome Icon Package
  http: ^0.12.2 # Api Connection Package
  intl: ^0.16.1 # By Locale Number, Date Format Package
  loading_overlay: ^0.2.1 # Loaging Progress - 프로그램의 정보가 모두 나타낼때까지 실행중임을 표시하는 패키지, JimsGatheringInformation.dart등에서 사용
  package_info: ^0.4.3 # Get Package Info - App Version을 알아내는데 사용하는 패키지, check.dart등에서 사용함
  progress_dialog: ^1.2.4 # Progress Dialog Package - login.dart에서 사용하는 실행중 Dialog표시 기능, Loading_overlay를 통해 간단히 Progress를 표시하는 방법도 있음
  progress_state_button: ^1.0.1 # Progress In Check Process - check.dart에서 사용하는 버튼형 Progress
  shared_preferences: ^0.5.10 # Global Variable of App (Same Cookie) Package - 쿠키를 대신하여 사용하는 패키지, login.dart, common.dart등에서 사용
  syncfusion_flutter_charts: ^18.3.48 # Chart
  syncfusion_flutter_datagrid: ^18.3.48-beta # Table
  url_launcher: ^5.7.2 # Url, Email, Tel, SMS Use - URL관련 처리를 지원하는 패키지, update.dart등에서 http url을 사용할 수 있음

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5 # App Icon Setting Package -> Ref. flutter_icons

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/jahwa.png
   - assets/lang/ko.json
   - assets/lang/vi.json
   - assets/lang/zh.json
   - assets/lang/en.json
  # - assets/JHMobile.db
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Malgun # Use Windwos Malgun Font
      fonts:
        - asset: fonts/malgun.ttf
        - asset: fonts/malgunbd.ttf
        - asset: fonts/malgunsl.ttf
    - family: NanumBrush # Use Naver Nanum Font
      fonts:
        - asset: fonts/NanumBrush.ttf
    - family: NanumPen # Use Naver Nanum Font
      fonts:
        - asset: fonts/NanumPen.ttf
  #        style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# App Name Setting
flutter_launcher_name:
  name: "JH Mobile"

# App Icon Setting
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"